fix(bench): bench.nu samply and node args escaping (#1529)
```
❯ ./bench.nu bench --accounts 1 --reset --mode dev --tps 9000 --duration 300 --preset tip20 --node-args="--builder.state-provider-metrics --engine.state-provider-metrics --engine.disable-prewarming --engine.legacy-state-root --engine.disable-state-cache"
Starting observability stack...
[+] Running 2/2
 ✔ Container tempo-bench-prometheus  Running                                                                0.0s
 ✔ Container tempo-bench-grafana     Running                                                                0.0s
Building tempo, tempo-bench: `cargo build --profile profiling --features jemalloc,asm-keccak --bin tempo --bin tempo-bench`...
    Finished `profiling` profile [optimized + debuginfo] target(s) in 1.96s
Starting 1 dev node(s)...
  Command: nu bench.nu node --mode dev --accounts 2 --skip-build --force --profile profiling --features jemalloc,asm-keccak --reset --node-args --builder.state-provider-metrics --engine.state-provider-metrics --engine.disable-prewarming --engine.legacy-state-root --engine.disable-state-cache
Error: nu::parser::unknown_flag

  x The `bench.nu node` command doesn't have flag `engine.state-provider-
  | metrics`.
   ,-[<commandline>:1:160]
 1 | main node --mode dev --accounts 2 --skip-build --force --profile profiling --features jemalloc,asm-keccak --reset --node-args --builder.state-provider-metrics --engine.state-provider-metrics --engine.disable-prewarming --engine.legacy-state-root --engine.disable-state-cache
   :                                                                                                                                                                ^^^^^^^^^^^^^^^|^^^^^^^^^^^^^^^
   :                                                                                                                                                                               `-- unknown flag
   `----
  help: Use `--help` to see available flags
```

We need to pass  the value of `--node-args` via `--node-args="..."`